//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicShop.WebUI.Resources.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElectronicShop.WebUI.Resources.Shared.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you don&apos;t have permission to access this page.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user already exists.
        /// </summary>
        public static string AdminRepeated {
            get {
                return ResourceManager.GetString("AdminRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an error occured while getting data from server, please refresh page and try again..
        /// </summary>
        public static string AjaxDataTableLoadingError {
            get {
                return ResourceManager.GetString("AjaxDataTableLoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has been expired, please login and try again.
        /// </summary>
        public static string AjaxNotAuthenticated {
            get {
                return ResourceManager.GetString("AjaxNotAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to access this page, please contact system administrator.
        /// </summary>
        public static string AjaxNotAuthorized {
            get {
                return ResourceManager.GetString("AjaxNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BarCode already exist.
        /// </summary>
        public static string BarCodeRepeated {
            get {
                return ResourceManager.GetString("BarCodeRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand already exists.
        /// </summary>
        public static string BrandRepeated {
            get {
                return ResourceManager.GetString("BrandRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Not Affected.
        /// </summary>
        public static string BrandsNotAffect {
            get {
                return ResourceManager.GetString("BrandsNotAffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client already exists.
        /// </summary>
        public static string ClientRepeated {
            get {
                return ResourceManager.GetString("ClientRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country already exist.
        /// </summary>
        public static string CountryRepeated {
            get {
                return ResourceManager.GetString("CountryRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Journey intersected with another journey for this merchandiser in the same store.
        /// </summary>
        public static string DateIntersected {
            get {
                return ResourceManager.GetString("DateIntersected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error has been Occured.
        /// </summary>
        public static string DeactivatedFaild {
            get {
                return ResourceManager.GetString("DeactivatedFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision already exist.
        /// </summary>
        public static string DecisionRepeated {
            get {
                return ResourceManager.GetString("DecisionRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same data already exists please select valid data and try again..
        /// </summary>
        public static string DetailsRepeated {
            get {
                return ResourceManager.GetString("DetailsRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date cannot be before join date.
        /// </summary>
        public static string EndDateBeforeJoinDate {
            get {
                return ResourceManager.GetString("EndDateBeforeJoinDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date cannot be before start date.
        /// </summary>
        public static string EndDateBeforeStartDate {
            get {
                return ResourceManager.GetString("EndDateBeforeStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter user name and password.
        /// </summary>
        public static string EnterUserNamePass {
            get {
                return ResourceManager.GetString("EnterUserNamePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while uploading photo.
        /// </summary>
        public static string ErrorUpload {
            get {
                return ResourceManager.GetString("ErrorUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, Error occured while calling server please refresh page and try again..
        /// </summary>
        public static string GeneralAjaxError {
            get {
                return ResourceManager.GetString("GeneralAjaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General error occured, please try again later.
        /// </summary>
        public static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This grade, decision and status already exists.
        /// </summary>
        public static string GradeDecisionRepeated {
            get {
                return ResourceManager.GetString("GradeDecisionRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image not found.
        /// </summary>
        public static string ImageNotFound {
            get {
                return ResourceManager.GetString("ImageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserted data is not valid.
        /// </summary>
        public static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user name or password.
        /// </summary>
        public static string InvalidLoginData {
            get {
                return ResourceManager.GetString("InvalidLoginData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserted data is not valid, please insert all required fields with correct value.
        /// </summary>
        public static string InvalidModelState {
            get {
                return ResourceManager.GetString("InvalidModelState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Not Affected.
        /// </summary>
        public static string ItemNotVaild {
            get {
                return ResourceManager.GetString("ItemNotVaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item already exist.
        /// </summary>
        public static string ItemRepeated {
            get {
                return ResourceManager.GetString("ItemRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchandiser already exists.
        /// </summary>
        public static string MerchandiserRepeated {
            get {
                return ResourceManager.GetString("MerchandiserRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modes Dates must between join date and end date.
        /// </summary>
        public static string ModeDatesRangBetweenStartEndDate {
            get {
                return ResourceManager.GetString("ModeDatesRangBetweenStartEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to export.
        /// </summary>
        public static string NoDataToExport {
            get {
                return ResourceManager.GetString("NoDataToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, No data seleced please select one or more and try again..
        /// </summary>
        public static string NoStoresSelected {
            get {
                return ResourceManager.GetString("NoStoresSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password must be different from old one.
        /// </summary>
        public static string OldNewPasswordSame {
            get {
                return ResourceManager.GetString("OldNewPasswordSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password not correct.
        /// </summary>
        public static string OldPasswordNotCorrect {
            get {
                return ResourceManager.GetString("OldPasswordNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order already exists.
        /// </summary>
        public static string OrderRepeated {
            get {
                return ResourceManager.GetString("OrderRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and confirm not matched.
        /// </summary>
        public static string PasswordsNoMatch {
            get {
                return ResourceManager.GetString("PasswordsNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to planogram already exists.
        /// </summary>
        public static string PlanogramRepeated {
            get {
                return ResourceManager.GetString("PlanogramRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range number already exists.
        /// </summary>
        public static string RangeRepeated {
            get {
                return ResourceManager.GetString("RangeRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Shelf and Width already exists.
        /// </summary>
        public static string ShelfBrandWidthRepeated {
            get {
                return ResourceManager.GetString("ShelfBrandWidthRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Size exceeded 2 Megabytes .
        /// </summary>
        public static string SizeExceed2M {
            get {
                return ResourceManager.GetString("SizeExceed2M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sku Not Exist.
        /// </summary>
        public static string SkuNotExist {
            get {
                return ResourceManager.GetString("SkuNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sku is not valid.
        /// </summary>
        public static string SkuNotValid {
            get {
                return ResourceManager.GetString("SkuNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock already exists.
        /// </summary>
        public static string StockRepeated {
            get {
                return ResourceManager.GetString("StockRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Not Affected.
        /// </summary>
        public static string StocksNotAffected {
            get {
                return ResourceManager.GetString("StocksNotAffected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store cluster already exists.
        /// </summary>
        public static string StoreClusterRepeated {
            get {
                return ResourceManager.GetString("StoreClusterRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Not Affected.
        /// </summary>
        public static string StoreNotAffected {
            get {
                return ResourceManager.GetString("StoreNotAffected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store already exists.
        /// </summary>
        public static string StoreRepeated {
            get {
                return ResourceManager.GetString("StoreRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Not exist.
        /// </summary>
        public static string SupplierBrandNotExist {
            get {
                return ResourceManager.GetString("SupplierBrandNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier already exists.
        /// </summary>
        public static string SupplierRepeated {
            get {
                return ResourceManager.GetString("SupplierRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists.
        /// </summary>
        public static string UserRepeated {
            get {
                return ResourceManager.GetString("UserRepeated", resourceCulture);
            }
        }
    }
}
