//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicShop.WebUI.Resources.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElectronicShop.WebUI.Resources.Shared.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24+.
        /// </summary>
        public static string _24Plus {
            get {
                return ResourceManager.GetString("24Plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABC.
        /// </summary>
        public static string Abc {
            get {
                return ResourceManager.GetString("Abc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A-Code.
        /// </summary>
        public static string ACode {
            get {
                return ResourceManager.GetString("ACode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated successfully.
        /// </summary>
        public static string ActivateSuccess {
            get {
                return ResourceManager.GetString("ActivateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel sheet data added successfuly..
        /// </summary>
        public static string AddedSuccessfuly {
            get {
                return ResourceManager.GetString("AddedSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Supplier User.
        /// </summary>
        public static string AddSupplierUserTitle {
            get {
                return ResourceManager.GetString("AddSupplierUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADesc.
        /// </summary>
        public static string ADesc {
            get {
                return ResourceManager.GetString("ADesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System users.
        /// </summary>
        public static string AdminsTitle {
            get {
                return ResourceManager.GetString("AdminsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Label.
        /// </summary>
        public static string ALabel {
            get {
                return ResourceManager.GetString("ALabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division.
        /// </summary>
        public static string ALevel {
            get {
                return ResourceManager.GetString("ALevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MerchEX.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string April {
            get {
                return ResourceManager.GetString("April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string Aug {
            get {
                return ResourceManager.GetString("Aug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.
        /// </summary>
        public static string Availability {
            get {
                return ResourceManager.GetString("Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability Dashboard.
        /// </summary>
        public static string AvailabilityDashboard {
            get {
                return ResourceManager.GetString("AvailabilityDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability Details.
        /// </summary>
        public static string AvailabilityDetailsTitle {
            get {
                return ResourceManager.GetString("AvailabilityDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability Detail.
        /// </summary>
        public static string AvailabilityDetailTitle {
            get {
                return ResourceManager.GetString("AvailabilityDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of Stock Report.
        /// </summary>
        public static string AvailabilityOutOfStockTitle {
            get {
                return ResourceManager.GetString("AvailabilityOutOfStockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.
        /// </summary>
        public static string AvailabilityPerformanceReport {
            get {
                return ResourceManager.GetString("AvailabilityPerformanceReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability .
        /// </summary>
        public static string AvailabilityReports {
            get {
                return ResourceManager.GetString("AvailabilityReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability Summary.
        /// </summary>
        public static string AvailabilitySummaryTitle {
            get {
                return ResourceManager.GetString("AvailabilitySummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avl.Status.
        /// </summary>
        public static string AvlStatus {
            get {
                return ResourceManager.GetString("AvlStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to home.
        /// </summary>
        public static string BackToHome {
            get {
                return ResourceManager.GetString("BackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        public static string Barcode {
            get {
                return ResourceManager.GetString("Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcodes.
        /// </summary>
        public static string BarCodesTitle {
            get {
                return ResourceManager.GetString("BarCodesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B-Code.
        /// </summary>
        public static string BCode {
            get {
                return ResourceManager.GetString("BCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BDesc.
        /// </summary>
        public static string BDesc {
            get {
                return ResourceManager.GetString("BDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string BLevel {
            get {
                return ResourceManager.GetString("BLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Name.
        /// </summary>
        public static string BrandName {
            get {
                return ResourceManager.GetString("BrandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brands.
        /// </summary>
        public static string BrandsMenu {
            get {
                return ResourceManager.GetString("BrandsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Width.
        /// </summary>
        public static string BrandWidth {
            get {
                return ResourceManager.GetString("BrandWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-Code.
        /// </summary>
        public static string C_Code {
            get {
                return ResourceManager.GetString("C-Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Manager.
        /// </summary>
        public static string CategoryManager {
            get {
                return ResourceManager.GetString("CategoryManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCode.
        /// </summary>
        public static string CCode {
            get {
                return ResourceManager.GetString("CCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDesc.
        /// </summary>
        public static string CDesc {
            get {
                return ResourceManager.GetString("CDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string CitiesTitle {
            get {
                return ResourceManager.GetString("CitiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CityId.
        /// </summary>
        public static string CityId {
            get {
                return ResourceManager.GetString("CityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C Label.
        /// </summary>
        public static string CLabel {
            get {
                return ResourceManager.GetString("CLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string CLevel {
            get {
                return ResourceManager.GetString("CLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string ClientsTitle {
            get {
                return ResourceManager.GetString("ClientsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed By.
        /// </summary>
        public static string ClosedBy {
            get {
                return ResourceManager.GetString("ClosedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed Sessions.
        /// </summary>
        public static string ClosedSessions {
            get {
                return ResourceManager.GetString("ClosedSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster.
        /// </summary>
        public static string Cluster {
            get {
                return ResourceManager.GetString("Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.Code.
        /// </summary>
        public static string ClusterCode {
            get {
                return ResourceManager.GetString("ClusterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.R.
        /// </summary>
        public static string ClusterRange {
            get {
                return ResourceManager.GetString("ClusterRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprehensive Freshness Report.
        /// </summary>
        public static string ComprehensiveFreshnessTitle {
            get {
                return ResourceManager.GetString("ComprehensiveFreshnessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string CountriesTitle {
            get {
                return ResourceManager.GetString("CountriesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivated successfully.
        /// </summary>
        public static string DeactivatedSuccess {
            get {
                return ResourceManager.GetString("DeactivatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string Dec {
            get {
                return ResourceManager.GetString("Dec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision.
        /// </summary>
        public static string DecisionStatus {
            get {
                return ResourceManager.GetString("DecisionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decisions.
        /// </summary>
        public static string DecisionTitle {
            get {
                return ResourceManager.GetString("DecisionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete successfully.
        /// </summary>
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate successfully, merchanidser schedules related to this store has been disabled.
        /// </summary>
        public static string DeleteSuccessScheduDisabled {
            get {
                return ResourceManager.GetString("DeleteSuccessScheduDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descion.
        /// </summary>
        public static string DescionMsg {
            get {
                return ResourceManager.GetString("DescionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details Search.
        /// </summary>
        public static string DetailsSearch {
            get {
                return ResourceManager.GetString("DetailsSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability Details.
        /// </summary>
        public static string DetailsTitle {
            get {
                return ResourceManager.GetString("DetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Supplier User.
        /// </summary>
        public static string EditSupplierUserTitle {
            get {
                return ResourceManager.GetString("EditSupplierUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel File Not Exist.
        /// </summary>
        public static string ExcelFileNotExist {
            get {
                return ResourceManager.GetString("ExcelFileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire Date.
        /// </summary>
        public static string ExpireDate {
            get {
                return ResourceManager.GetString("ExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Details.
        /// </summary>
        public static string ExportDetailsDetailExcel {
            get {
                return ResourceManager.GetString("ExportDetailsDetailExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Summary.
        /// </summary>
        public static string ExportDetailsMasterExcel {
            get {
                return ResourceManager.GetString("ExportDetailsMasterExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Excel.
        /// </summary>
        public static string ExportExcel {
            get {
                return ResourceManager.GetString("ExportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export excel for selected stores.
        /// </summary>
        public static string ExportMasterExcel {
            get {
                return ResourceManager.GetString("ExportMasterExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Not Found (Active Stock).
        /// </summary>
        public static string ExportNotFound {
            get {
                return ResourceManager.GetString("ExportNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        public static string Feb {
            get {
                return ResourceManager.GetString("Feb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Scan.
        /// </summary>
        public static string FirstHour {
            get {
                return ResourceManager.GetString("FirstHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found.
        /// </summary>
        public static string Found {
            get {
                return ResourceManager.GetString("Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeScanMode.
        /// </summary>
        public static string FreeScanMode {
            get {
                return ResourceManager.GetString("FreeScanMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Scan.
        /// </summary>
        public static string FreeScanTitle {
            get {
                return ResourceManager.GetString("FreeScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freshness By Region.
        /// </summary>
        public static string FreshnessByRegion {
            get {
                return ResourceManager.GetString("FreshnessByRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freshness Details.
        /// </summary>
        public static string FreshnessDetailsMenu {
            get {
                return ResourceManager.GetString("FreshnessDetailsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freshness .
        /// </summary>
        public static string FreshnessDetailsTitle {
            get {
                return ResourceManager.GetString("FreshnessDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freshness.
        /// </summary>
        public static string FreshnessPerformanceReport {
            get {
                return ResourceManager.GetString("FreshnessPerformanceReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freshness.
        /// </summary>
        public static string FreshnessReports {
            get {
                return ResourceManager.GetString("FreshnessReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fri.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geo Settings.
        /// </summary>
        public static string GeoSetting {
            get {
                return ResourceManager.GetString("GeoSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade decisions and status.
        /// </summary>
        public static string GradeDecisionTitle {
            get {
                return ResourceManager.GetString("GradeDecisionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01:00.
        /// </summary>
        public static string Hour01 {
            get {
                return ResourceManager.GetString("Hour01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02:00.
        /// </summary>
        public static string Hour02 {
            get {
                return ResourceManager.GetString("Hour02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 03:00.
        /// </summary>
        public static string Hour03 {
            get {
                return ResourceManager.GetString("Hour03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 04:00.
        /// </summary>
        public static string Hour04 {
            get {
                return ResourceManager.GetString("Hour04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 05:00.
        /// </summary>
        public static string Hour05 {
            get {
                return ResourceManager.GetString("Hour05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 06:00.
        /// </summary>
        public static string Hour06 {
            get {
                return ResourceManager.GetString("Hour06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 07:00.
        /// </summary>
        public static string Hour07 {
            get {
                return ResourceManager.GetString("Hour07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 08:00.
        /// </summary>
        public static string Hour08 {
            get {
                return ResourceManager.GetString("Hour08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 09:00.
        /// </summary>
        public static string Hour09 {
            get {
                return ResourceManager.GetString("Hour09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10:00.
        /// </summary>
        public static string Hour10 {
            get {
                return ResourceManager.GetString("Hour10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11:00.
        /// </summary>
        public static string Hour11 {
            get {
                return ResourceManager.GetString("Hour11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12:00.
        /// </summary>
        public static string Hour12 {
            get {
                return ResourceManager.GetString("Hour12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13:00.
        /// </summary>
        public static string Hour13 {
            get {
                return ResourceManager.GetString("Hour13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14:00.
        /// </summary>
        public static string Hour14 {
            get {
                return ResourceManager.GetString("Hour14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15:00.
        /// </summary>
        public static string Hour15 {
            get {
                return ResourceManager.GetString("Hour15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16:00.
        /// </summary>
        public static string Hour16 {
            get {
                return ResourceManager.GetString("Hour16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17:00.
        /// </summary>
        public static string Hour17 {
            get {
                return ResourceManager.GetString("Hour17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18:00.
        /// </summary>
        public static string Hour18 {
            get {
                return ResourceManager.GetString("Hour18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19:00.
        /// </summary>
        public static string Hour19 {
            get {
                return ResourceManager.GetString("Hour19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20:00.
        /// </summary>
        public static string Hour20 {
            get {
                return ResourceManager.GetString("Hour20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21:00.
        /// </summary>
        public static string Hour21 {
            get {
                return ResourceManager.GetString("Hour21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22:00.
        /// </summary>
        public static string Hour22 {
            get {
                return ResourceManager.GetString("Hour22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23:00.
        /// </summary>
        public static string Hour23 {
            get {
                return ResourceManager.GetString("Hour23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00:00.
        /// </summary>
        public static string Hour24 {
            get {
                return ResourceManager.GetString("Hour24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File uploaded successfully, but there is not data to display, it may be no changes or addition to records or excel data is not valid.
        /// </summary>
        public static string ImportExcelUploadFail {
            get {
                return ResourceManager.GetString("ImportExcelUploadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File uploaded successfully, a sample of file data is loaded in the table below, please review it then click save to save changes.
        /// </summary>
        public static string ImportExcelUploadSuccess {
            get {
                return ResourceManager.GetString("ImportExcelUploadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress.
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserted Successfully.
        /// </summary>
        public static string InsertSuccess {
            get {
                return ResourceManager.GetString("InsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsMSL.
        /// </summary>
        public static string IsMsl {
            get {
                return ResourceManager.GetString("IsMsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Decision Status.
        /// </summary>
        public static string ItemDecisionStatus {
            get {
                return ResourceManager.GetString("ItemDecisionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Desc.
        /// </summary>
        public static string ItemDesc {
            get {
                return ResourceManager.GetString("ItemDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ItemDescription {
            get {
                return ResourceManager.GetString("ItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item NO..
        /// </summary>
        public static string ItemNumber {
            get {
                return ResourceManager.GetString("ItemNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Admin.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Barcodes.
        /// </summary>
        public static string ItemsBarcodes {
            get {
                return ResourceManager.GetString("ItemsBarcodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decisions.
        /// </summary>
        public static string ItemsDecisions {
            get {
                return ResourceManager.GetString("ItemsDecisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade decisions and status.
        /// </summary>
        public static string ItemsGradeDecisions {
            get {
                return ResourceManager.GetString("ItemsGradeDecisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string ItemsTitle {
            get {
                return ResourceManager.GetString("ItemsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string Jan {
            get {
                return ResourceManager.GetString("Jan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JDA.
        /// </summary>
        public static string JdaStatus {
            get {
                return ResourceManager.GetString("JdaStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Journey data intersected with exist journies please select valid dates and try again. .
        /// </summary>
        public static string JourneyRepeated {
            get {
                return ResourceManager.GetString("JourneyRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchandiser Schedule.
        /// </summary>
        public static string JourneyTitle {
            get {
                return ResourceManager.GetString("JourneyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string July {
            get {
                return ResourceManager.GetString("July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string June {
            get {
                return ResourceManager.GetString("June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Scan.
        /// </summary>
        public static string LastHour {
            get {
                return ResourceManager.GetString("LastHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastLoginDate.
        /// </summary>
        public static string LastLoginDate {
            get {
                return ResourceManager.GetString("LastLoginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Location.
        /// </summary>
        public static string MapLocation {
            get {
                return ResourceManager.GetString("MapLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string Mar {
            get {
                return ResourceManager.GetString("Mar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.G.
        /// </summary>
        public static string MaterialGrade {
            get {
                return ResourceManager.GetString("MaterialGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.T.
        /// </summary>
        public static string MaterialType {
            get {
                return ResourceManager.GetString("MaterialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchandiser.
        /// </summary>
        public static string Merchandiser {
            get {
                return ResourceManager.GetString("Merchandiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRM ID.
        /// </summary>
        public static string MerchandiserId {
            get {
                return ResourceManager.GetString("MerchandiserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchandiser Name.
        /// </summary>
        public static string MerchandiserName {
            get {
                return ResourceManager.GetString("MerchandiserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some merchandiser data already exsists please select unique name and username and try again..
        /// </summary>
        public static string MerchandiserRepeated {
            get {
                return ResourceManager.GetString("MerchandiserRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchandiser Admin.
        /// </summary>
        public static string MerchandiserSettings {
            get {
                return ResourceManager.GetString("MerchandiserSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchandisers.
        /// </summary>
        public static string MerchandiserTitle {
            get {
                return ResourceManager.GetString("MerchandiserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission Status.
        /// </summary>
        public static string MissionStatus {
            get {
                return ResourceManager.GetString("MissionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MobileNumber.
        /// </summary>
        public static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Of Shelves.
        /// </summary>
        public static string NoOfShelves {
            get {
                return ResourceManager.GetString("NoOfShelves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Photos Found.
        /// </summary>
        public static string NoPhotosFound {
            get {
                return ResourceManager.GetString("NoPhotosFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Active.
        /// </summary>
        public static string NotActive {
            get {
                return ResourceManager.GetString("NotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available.
        /// </summary>
        public static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Scanned.
        /// </summary>
        public static string NotScanned {
            get {
                return ResourceManager.GetString("NotScanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string Nov {
            get {
                return ResourceManager.GetString("Nov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string Oct {
            get {
                return ResourceManager.GetString("Oct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of.
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ongoing.
        /// </summary>
        public static string OnGoing {
            get {
                return ResourceManager.GetString("OnGoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open By.
        /// </summary>
        public static string OpenBy {
            get {
                return ResourceManager.GetString("OpenBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Sessions.
        /// </summary>
        public static string OpenSessions {
            get {
                return ResourceManager.GetString("OpenSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTC.
        /// </summary>
        public static string Otc {
            get {
                return ResourceManager.GetString("Otc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully, you will be redirected to login.
        /// </summary>
        public static string PasswordChangeSuccess {
            get {
                return ResourceManager.GetString("PasswordChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        public static string PerformanceReportMenu {
            get {
                return ResourceManager.GetString("PerformanceReportMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchandisers Performance Report.
        /// </summary>
        public static string PerformanceReportTitle {
            get {
                return ResourceManager.GetString("PerformanceReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy Only.
        /// </summary>
        public static string PharmacyOnly {
            get {
                return ResourceManager.GetString("PharmacyOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy With Code.
        /// </summary>
        public static string PharmacyWithCode {
            get {
                return ResourceManager.GetString("PharmacyWithCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlanoGram Backdoor.
        /// </summary>
        public static string PlanoGramBackdoorTitle {
            get {
                return ResourceManager.GetString("PlanoGramBackdoorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string PlanogramDetails {
            get {
                return ResourceManager.GetString("PlanogramDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlanoGram Details Report.
        /// </summary>
        public static string PlanoGramDetailsReportTitle {
            get {
                return ResourceManager.GetString("PlanoGramDetailsReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planogram Photos.
        /// </summary>
        public static string PlanoGramPhotosTitle {
            get {
                return ResourceManager.GetString("PlanoGramPhotosTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planogram.
        /// </summary>
        public static string PlanogramReportTitle {
            get {
                return ResourceManager.GetString("PlanogramReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planogram Admin.
        /// </summary>
        public static string PlanogramSettings {
            get {
                return ResourceManager.GetString("PlanogramSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string PlanogramSummary {
            get {
                return ResourceManager.GetString("PlanogramSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planogram Summary Report.
        /// </summary>
        public static string PlanoGramSummaryReportTitle {
            get {
                return ResourceManager.GetString("PlanoGramSummaryReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planogram.
        /// </summary>
        public static string PlanogramTitle {
            get {
                return ResourceManager.GetString("PlanogramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select item.
        /// </summary>
        public static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planogram priority.
        /// </summary>
        public static string PriorityTitle {
            get {
                return ResourceManager.GetString("PriorityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Data.
        /// </summary>
        public static string ProductData {
            get {
                return ResourceManager.GetString("ProductData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Area.
        /// </summary>
        public static string PurchaseArea {
            get {
                return ResourceManager.GetString("PurchaseArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session ID.
        /// </summary>
        public static string RefNumber {
            get {
                return ResourceManager.GetString("RefNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions.
        /// </summary>
        public static string RegionsTitle {
            get {
                return ResourceManager.GetString("RegionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string ReportSummaryTitle {
            get {
                return ResourceManager.GetString("ReportSummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP.VAT.
        /// </summary>
        public static string SalesPrice {
            get {
                return ResourceManager.GetString("SalesPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP Status.
        /// </summary>
        public static string SapStatus {
            get {
                return ResourceManager.GetString("SapStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP Stock.
        /// </summary>
        public static string SAPStock {
            get {
                return ResourceManager.GetString("SAPStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Successfully.
        /// </summary>
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Date.
        /// </summary>
        public static string ScanDate {
            get {
                return ResourceManager.GetString("ScanDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanned.
        /// </summary>
        public static string Scanned {
            get {
                return ResourceManager.GetString("Scanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanned.
        /// </summary>
        public static string ScannedName {
            get {
                return ResourceManager.GetString("ScannedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanned Planograms.
        /// </summary>
        public static string ScannedPlanograms {
            get {
                return ResourceManager.GetString("ScannedPlanograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScannedSKUs.
        /// </summary>
        public static string ScannedSKUs {
            get {
                return ResourceManager.GetString("ScannedSKUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.S.
        /// </summary>
        public static string ScanningStatus {
            get {
                return ResourceManager.GetString("ScanningStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Status.
        /// </summary>
        public static string ScanStatus {
            get {
                return ResourceManager.GetString("ScanStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Criteria.
        /// </summary>
        public static string SearchCriteria {
            get {
                return ResourceManager.GetString("SearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Result.
        /// </summary>
        public static string SearchResult {
            get {
                return ResourceManager.GetString("SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string Sep {
            get {
                return ResourceManager.GetString("Sep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session End Date.
        /// </summary>
        public static string SessionEnd {
            get {
                return ResourceManager.GetString("SessionEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session End Date.
        /// </summary>
        public static string SessionEndDate {
            get {
                return ResourceManager.GetString("SessionEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Id.
        /// </summary>
        public static string SessionId {
            get {
                return ResourceManager.GetString("SessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Start Date.
        /// </summary>
        public static string SessionStart {
            get {
                return ResourceManager.GetString("SessionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Start Date.
        /// </summary>
        public static string SessionStartDate {
            get {
                return ResourceManager.GetString("SessionStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Status.
        /// </summary>
        public static string SessionStatus {
            get {
                return ResourceManager.GetString("SessionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share %.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share of shelf.
        /// </summary>
        public static string ShareOfShelfMenu {
            get {
                return ResourceManager.GetString("ShareOfShelfMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Shelf Width.
        /// </summary>
        public static string ShelfBrandWidthTitle {
            get {
                return ResourceManager.GetString("ShelfBrandWidthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelf Configuration.
        /// </summary>
        public static string ShelfConfigurationTitle {
            get {
                return ResourceManager.GetString("ShelfConfigurationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sku.
        /// </summary>
        public static string Sku {
            get {
                return ResourceManager.GetString("Sku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some records added successfuly and some records have values already exists edit this values and try again..
        /// </summary>
        public static string SomeAddedSuccessfuly {
            get {
                return ResourceManager.GetString("SomeAddedSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong please try again later.
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelf config..
        /// </summary>
        public static string SosConfigMenu {
            get {
                return ResourceManager.GetString("SosConfigMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string SosDetailsMenu {
            get {
                return ResourceManager.GetString("SosDetailsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SR.
        /// </summary>
        public static string Sr {
            get {
                return ResourceManager.GetString("Sr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Session.
        /// </summary>
        public static string StartSession {
            get {
                return ResourceManager.GetString("StartSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock On Hand.
        /// </summary>
        public static string StockOnHand {
            get {
                return ResourceManager.GetString("StockOnHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Stocks.
        /// </summary>
        public static string StockTitle {
            get {
                return ResourceManager.GetString("StockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        public static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Cluster.
        /// </summary>
        public static string StoreClusterTitle {
            get {
                return ResourceManager.GetString("StoreClusterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Code.
        /// </summary>
        public static string StoreCode {
            get {
                return ResourceManager.GetString("StoreCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stores Cluster.
        /// </summary>
        public static string StoresClusterTitle {
            get {
                return ResourceManager.GetString("StoresClusterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Admin.
        /// </summary>
        public static string StoreSetting {
            get {
                return ResourceManager.GetString("StoreSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stores.
        /// </summary>
        public static string StoresTitle {
            get {
                return ResourceManager.GetString("StoresTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested Brand Width.
        /// </summary>
        public static string SuggestedBrandWidth {
            get {
                return ResourceManager.GetString("SuggestedBrandWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers.
        /// </summary>
        public static string SuppliersTitle {
            get {
                return ResourceManager.GetString("SuppliersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string SupplierUserTitle {
            get {
                return ResourceManager.GetString("SupplierUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Admin.
        /// </summary>
        public static string SystemAdmin {
            get {
                return ResourceManager.GetString("SystemAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TMR ID.
        /// </summary>
        public static string TMRID {
            get {
                return ResourceManager.GetString("TMRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TMR Name.
        /// </summary>
        public static string TMRName {
            get {
                return ResourceManager.GetString("TMRName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Planograms.
        /// </summary>
        public static string TotalPlanograms {
            get {
                return ResourceManager.GetString("TotalPlanograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Shelf Width.
        /// </summary>
        public static string TotalShelfWidth {
            get {
                return ResourceManager.GetString("TotalShelfWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tue.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessful Scans.
        /// </summary>
        public static string UnsuccessfulScans {
            get {
                return ResourceManager.GetString("UnsuccessfulScans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsucessful scan.
        /// </summary>
        public static string UnsuccessfulScansReportMenu {
            get {
                return ResourceManager.GetString("UnsuccessfulScansReportMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Successfully.
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserActionDate.
        /// </summary>
        public static string UserActionDate {
            get {
                return ResourceManager.GetString("UserActionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        public static string Vendor {
            get {
                return ResourceManager.GetString("Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor No.
        /// </summary>
        public static string VendorId {
            get {
                return ResourceManager.GetString("VendorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Name.
        /// </summary>
        public static string VendorName {
            get {
                return ResourceManager.GetString("VendorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor No..
        /// </summary>
        public static string VendorNum {
            get {
                return ResourceManager.GetString("VendorNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V.Number.
        /// </summary>
        public static string VNumber {
            get {
                return ResourceManager.GetString("VNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wed.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Date.
        /// </summary>
        public static string WorkingDate {
            get {
                return ResourceManager.GetString("WorkingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone.
        /// </summary>
        public static string Zone {
            get {
                return ResourceManager.GetString("Zone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zones.
        /// </summary>
        public static string ZoneTitle {
            get {
                return ResourceManager.GetString("ZoneTitle", resourceCulture);
            }
        }
    }
}
